version: "3"

services:
    compro-grc-prod:
        build: .
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.compro-grc-prod-http.entrypoints=web"
            - "traefik.http.routers.compro-grc-prod-http.rule=Host(`comprogrc.appstage.my.id`)"
            - "traefik.http.routers.compro-grc-prod-http.middlewares=redirect-to-https"
            - "traefik.http.routers.compro-grc-prod.entrypoints=websecure"
            - "traefik.http.routers.compro-grc-prod.tls.certresolver=myresolver"
            - "traefik.http.routers.compro-grc-prod.rule=Host(`comprogrc.appstage.my.id`)"
            - "traefik.http.routers.compro-grc-prod.tls=true"
        restart: always
        networks:
            - traefik_default
        volumes:
            - /root/workspace/testing-app/compro-grc-upload/uploads:/app/uploads
        env_file:
            - .env
networks:
    traefik_default:
        external: true
